# Generated by Django 4.2.2 on 2023-07-01 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthBlob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(default="", max_length=100)),
                (
                    "created",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2023, 7, 1, 22, 27, 7, 334851, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
            ],
        ),
    ]
